contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #transfuse channel"
    url: https://nfcore.slack.com/channels/transfuse
    about: Discussion about the nf-core/transfuse pipeline
